version: "3"

services:
  app:
    container_name: cscore-api
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./env/dev
    volumes:
      - "./src:/app/src"
      - "./lib:/app/lib"
      - "./logs:/app/logs"
    ports:
      - 4000:4000
      - 5858:5858
    entrypoint:
      - ./entrypoint.sh
      - ./node_modules/.bin/nodemon
      - ./bin/server

  postgres:
    image: postgres:9.6.5-alpine
    container_name: cscore-db
    volumes:
      - "postgres:/var/lib/postgresql/data"
    ports:
      - 5433:5432
    env_file:
      - ./env/dev

volumes:
  postgres:
